[regressions]
tiny = [
    { name = "test1", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test2", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test3", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test4", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test5", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test6", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test7", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test8", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test9", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test10", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test11", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test12", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test13", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test14", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test15", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test16", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test17", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
]
medium = [
    { name = "test1", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test2", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test3", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test4", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test5", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test6", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test7", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test8", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test9", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test10", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test11", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test12", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test13", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test14", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test15", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test16", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test17", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test18", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test19", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test20", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test21", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test22", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test23", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test24", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test25", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test26", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test27", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test28", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test29", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test30", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test31", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test32", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test33", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test34", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test35", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test36", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test37", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test38", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test39", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test40", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test41", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test42", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test43", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test44", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test45", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test46", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test47", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test48", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test49", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test50", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
    { name = "test51", exec = "@jinja {{this.paths.app_root_dir}}/bin/run" },
]
