logging:
  handlers:
    file:
      path: "@jinja {{this.paths.user_log_file}}"
      level: DEBUG
    console:
      level: FATAL
      tracebacks_show_locals: true
    rotating_file:
      path: "@jinja {{this.paths.user_rotating_log_file}}"

  formatters:
    default:
      fmt: "%(message)s"
      datefmt: "[%x %X]"
    child:
      fmt: "%(asctime)s %(levelname)5s - %(filename)5s:%(lineno)-4d - %(message)s"
      datefmt: "[%x %X]"
