logging:
  handlers:
    file:
      path: "@get this.paths.user_log_file"
      level: DEBUG
      tracebacks_show_locals: >-
        @bool @jinja {%- if this.cli.params.verbosity == 'DEBUG' -%}
            True
        {%- else -%}
            False
        {%- endif -%}"
    console:
      level: INFO
    rotating_file:
      level: DEBUG
      path: "@get this.paths.user_rotating_log_file"

  formatters:
    default:
      fmt: "%(message)s"
      datefmt: "[%x %X]"
    child:
      fmt: "%(asctime)s %(levelname)5s - %(filename)5s:%(lineno)-4d - %(message)s"
      datefmt: "[%x %X]"
